# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Run Playwright Tests
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PlaywrightTests
    displayName: Playwright Tests
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: self

    - script: docker build -t playwright-tests .
      displayName: 'Build Docker Image'

    - script: |
        docker run --rm \
          -v "$(Build.SourcesDirectory)/playwright-report:/app/playwright-report" \
          playwright-tests
      displayName: 'Run Playwright Tests in Docker'
      continueOnError: true

    - task: PublishPipelineArtifact@1
      displayName: 'Save Playwright Report as Artifact'
      condition: succeededOrFailed()
      inputs:
        targetPath: '$(Build.SourcesDirectory)/playwright-report'
        artifact: 'playwright-report'
        publishLocation: 'pipeline'