name: Deploy Playwright Report to GitGub Pages
on:
  push:
    branches:
    - main, master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t playwright-tests .
    - name: Run Playwright tests in Docker
      run: docker run --rm -v "${{ github.workspace }}/playwright-report:/app/playwright-report" playwright-tests
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: plawywright-report
        path: playwright-report
        retention-days: 30

    - name: Deploy to GitGub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages
    - name: Add link to report in summary
      run: |
        echo "## Test Report" >> $GITHUB_STEP_SUMMARY
        echo "[View Test Report](https://${{ github.actor }}.github.io/test/playwright-report/)" >> $GITHUB_STEP_SUMMARY
  # - name: Add link to report in summary
  #   run: |
  #     echo "## Test Report" >> $GITHUB_STEP_SUMMARY
  #     echo "[View Test Report](https://${{ github.actor }}.github.io/test/playwright-report/)" >> $GITHUB_STEP_SUMMARY
